version: "3"

services:
    seed_base_router:
        build: ./Base_Images/router
        image: seed_base_router
        container_name: seed-base-router
        command: " echo 'exiting...' "

    seed_base_host:
        build: ./Base_Images/host
        image: seed_base_host
        container_name: seed-base-host
        command: " echo 'exiting...' "


    backbone1_router:
        build:
            context: ./router
            args:
                BIRD_CONF: backbone1_bird.conf
        image: backbone1-router
        container_name: backbone1-router
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
        networks:
            backbone-c-net-2:
                ipv4_address: 10.15.2.3
            backbone-a-net-2:
                ipv4_address: 10.16.2.3

    backbone2_router:
        build:
            context: ./router
            args:
                BIRD_CONF: backbone2_bird.conf
        image: backbone2-router
        container_name: backbone2-router
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
        networks:
            backbone-c-net-1:
                ipv4_address: 10.15.1.3
            backbone-c-net-3:
                ipv4_address: 10.15.3.3
            backbone-c-net-4:
                ipv4_address: 10.15.4.3
            backbone-c-net-5:
                ipv4_address: 10.15.5.3
            backbone-a-net-1:
                ipv4_address: 10.16.1.3
            backbone-a-net-3:
                ipv4_address: 10.16.3.3
            backbone-a-net-4:
                ipv4_address: 10.16.4.3
            backbone-a-net-5:
                ipv4_address: 10.16.5.3

    backbone3_router:
        build:
            context: ./router
            args:
                BIRD_CONF: backbone3_bird.conf
        image: backbone3-router
        container_name: backbone3-router
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
        networks:
            backbone-c-net-6:
                ipv4_address: 10.15.6.3
            backbone-a-net-6:
                ipv4_address: 10.16.6.3

    c1_router:
        build:
            context: ./router
            args:
                BIRD_CONF: crouter1_bird.conf
        image: c1-router
        container_name: c1-router
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
        networks:
            backbone-c-net-1:
                ipv4_address: 10.15.1.2
            backbone-c-net-2:
                ipv4_address: 10.15.2.2
            backbone-c-net-3:
                ipv4_address: 10.15.3.2
            c-net-1:
                ipv4_address: 10.100.1.15

    
    c2_router:
        build:
            context: ./router
            args:
                BIRD_CONF: crouter2_bird.conf
        image: c2-router
        container_name: c2-router
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
        networks:
            backbone-c-net-4:
                ipv4_address: 10.15.4.2
            backbone-c-net-5:
                ipv4_address: 10.15.5.2
            backbone-c-net-6:
                ipv4_address: 10.15.6.2
            c-net-2:
                ipv4_address: 10.100.2.15

    
    a1_router:
        build:
            context: ./router
            args:
                BIRD_CONF: arouter1_bird.conf
        image: a1-router
        container_name: a1-router
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
        networks:
            backbone-a-net-1:
                ipv4_address: 10.16.1.2
            backbone-a-net-2:
                ipv4_address: 10.16.2.2
            backbone-a-net-3:
                ipv4_address: 10.16.3.2
            a-net-1:
                ipv4_address: 10.101.1.15

    
    a2_router:
        build:
            context: ./router
            args:
                BIRD_CONF: arouter2_bird.conf
        image: a2-router
        container_name: a2-router
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
        networks:
            backbone-a-net-4:
                ipv4_address: 10.16.4.2
            backbone-a-net-5:
                ipv4_address: 10.16.5.2
            backbone-a-net-6:
                ipv4_address: 10.16.6.2
            a-net-2:
                ipv4_address: 10.101.2.15


networks:
    backbone-c-net-1:
        ipam:
            config:
                - subnet: 10.15.1.0/24
    backbone-c-net-2:
        ipam:
            config:
                - subnet: 10.15.2.0/24
    backbone-c-net-3:
        ipam:
            config:
                - subnet: 10.15.3.0/24
    backbone-c-net-4:
        ipam:
            config:
                - subnet: 10.15.4.0/24
    backbone-c-net-5:    
        ipam:
            config:
                - subnet: 10.15.5.0/24
    backbone-c-net-6:
        ipam:
            config:
                - subnet: 10.15.6.0/24

    backbone-a-net-1:
        ipam:
            config:
                - subnet: 10.16.1.0/24
    backbone-a-net-2:
        ipam:
            config:
                - subnet: 10.16.2.0/24
    backbone-a-net-3:
        ipam:
            config:
                - subnet: 10.16.3.0/24
    backbone-a-net-4:
        ipam:
            config:
                - subnet: 10.16.4.0/24
    backbone-a-net-5:
        ipam:
            config:
                - subnet: 10.16.5.0/24
    backbone-a-net-6:
        ipam:
            config:
                - subnet: 10.16.6.0/24

    a-net-1:
        ipam:
            config:
                - subnet: 10.101.1.0/24

    a-net-2:
        ipam:
            config:
                - subnet: 10.101.2.0/24

    c-net-1:
        ipam:
            config:
                - subnet: 10.100.1.0/24
    c-net-2:
        ipam:
            config:
                - subnet: 10.100.2.0/24
          

